# Generated by Django 5.1.4 on 2026-09-26 03:28

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True, verbose_name='线路名称')),
                ('description', models.CharField(blank=True, default='', max_length=500, verbose_name='线路简介')),
                ('difficulty', models.CharField(choices=[('family', '亲子'), ('adult', '成人'), ('pro', '专业')], default='adult', max_length=16, verbose_name='难度')),
                ('capacity', models.PositiveIntegerField(verbose_name='队伍名额')),
                ('register_deadline', models.DateTimeField(verbose_name='报名截止时间')),
                ('started', models.BooleanField(default=False, verbose_name='赛事是否已开始')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'course',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Checkpoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(verbose_name='打卡顺序')),
                ('code', models.CharField(max_length=40, verbose_name='检查点编码')),
                ('name', models.CharField(max_length=120, verbose_name='检查点名称')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checkpoints', to='domain.course')),
            ],
            options={
                'db_table': 'checkpoint',
                'ordering': ['course_id', 'order'],
                'unique_together': {('course', 'order')},
            },
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='队伍名称')),
                ('leader_name', models.CharField(max_length=80, verbose_name='队长姓名')),
                ('contact', models.CharField(blank=True, default='', max_length=120, verbose_name='联系方式')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teams', to='domain.course')),
            ],
            options={
                'db_table': 'team',
                'ordering': ['id'],
                'unique_together': {('course', 'name')},
            },
        ),
        migrations.CreateModel(
            name='Punch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('punched_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='打卡时间')),
                ('checkpoint', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='domain.checkpoint')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='punches', to='domain.team')),
            ],
            options={
                'db_table': 'punch',
                'ordering': ['punched_at'],
                'unique_together': {('team', 'checkpoint')},
            },
        ),
        migrations.CreateModel(
            name='CourseMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('member_name', models.CharField(max_length=80, verbose_name='成员姓名')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='domain.course')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='domain.team')),
            ],
            options={
                'db_table': 'course_membership',
                'unique_together': {('course', 'member_name')},
            },
        ),
        migrations.CreateModel(
            name='TeamMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, verbose_name='成员姓名')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='domain.team')),
            ],
            options={
                'db_table': 'team_member',
                'ordering': ['id'],
                'unique_together': {('team', 'name')},
            },
        ),
    ]
